services:
  postgres:
    image: postgres:15-alpine

    container_name: dam-postgres

    restart: always

    env_file:
      - .env.local

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'

    volumes:
      - dam-postgres-data:/var/lib/postgresql/data

    networks:
      - dam-network

    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 5

  mongodb:
    image: mongo:7

    container_name: dam-mongo

    restart: always

    env_file:
      - .env.local

    environment:
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=${MONGO_DB}

    ports:
      - '27017:27017'

    volumes:
      - dam_mongo_data:/data/db

    networks:
      - dam-network

  minio:
    image: minio/minio:latest

    container_name: dam_assets-minio

    restart: always

    env_file:
      - .env.local

    ports:
      - '9000:9000'
      - '9001:9001'

    volumes:
      - minio_data:/data

    command: server /data --console-address ":9001"

    networks:
      - dam-network

  rabbitmq:
    image: rabbitmq:3-management

    container_name: rabbitmq

    hostname: rabbitmq

    ports:
      - '5672:5672'
      - '15672:15672'

    env_file:
      - .env.local

    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
      - RABBITMQ_DEFAULT_VHOST=dam

    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5

    restart: unless-stopped

    networks:
      - dam-network

  redis:
    image: redis:7-alpine

    container_name: redis

    hostname: redis

    env_file:
      - .env.local

    healthcheck:
      test: ['CMD-SHELL', 'redis-cli ping | grep PONG']
      interval: 1s
      timeout: 3s
      retries: 5

    command: ['redis-server']

    ports:
      - '6379:6379'
    restart: unless-stopped

    volumes:
      - redis-data:/data
      
    networks:
      - dam-network

volumes:
  dam-postgres-data:
    external: true
  dam_mongo_data:
    external: true
  minio_data:
    external: true
  rabbitmq_data:
  redis-data:
    driver: local

networks:
  dam-network:
    external: true
