import { transporter } from '@dam/config';
import { env_config_variable } from '@dam/config';
import { logger } from '@dam/config';

export const sendReportEmail = async (
  email: string,
  buffer: Buffer,
  meta: { scope: string; fromStr?: string; toStr?: string },
): Promise<void> => {
  try {
    await transporter.sendMail({
      from: env_config_variable.MAIL.FROM,
      to: email,
      subject: `Your ${meta.scope} analytics report is ready`,
      html: `
        <div style="font-family:sans-serif; max-width:600px; margin:0 auto; padding:24px;">
          <h2 style="color:#111;">Your Analytics Report is Ready</h2>
          <p style="color:#444;">
            Your <strong>${meta.scope}</strong> overview report for the period
            <strong>${meta.fromStr}</strong> to <strong>${meta.toStr}</strong>
            has been generated successfully. Please find the PDF attached.
          </p>
          <p style="margin-top:24px; color:#999; font-size:12px;">
            This report was generated by DAM Platform.
          </p>
        </div>
      `,
      attachments: [
        {
          filename: `${meta.scope}_report_${meta.fromStr}_${meta.toStr}.pdf`,
          content: buffer,
          contentType: 'application/pdf',
        },
      ],
    });

    logger.info('Report email sent', {
      email,
      scope: meta.scope,
      from: meta.fromStr,
      to: meta.toStr,
    });
  } catch (error) {
    logger.error('Failed to send report email', {
      email,
      scope: meta.scope,
      error,
    });
    throw new Error('Failed to send report email');
  }
};
